version: !!str 3.9

networks:
  newsvit-br:
    name: vdi-br
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.100.0/24
         gateway: 192.168.100.1

services:
  vdi-db:
    image: mariadb:10.6
    container_name: "vdi-panel-db"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      newsvit-br:
        ipv4_address: 192.168.100.2
    environment:
      - MYSQL_ROOT_PASSWORD=masoud123
      - MYSQL_DATABASE=${VDI_MYSQL_DB}
      - MYSQL_USER=${VDI_MYSQL_USER}
      - MYSQL_PASSWORD=${VDI_MYSQL_PASSWORD}
    expose:
      - ${VDI_MYSQL_PORT}

  vdi-panel:
    dns:
      - 178.22.122.100
      - 185.51.200.2
    container_name: "vdi-panel-web"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      vdi-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - ${VDI_PANEL_PORT}:80

    networks:
      newsvit-br:
        ipv4_address: 192.168.100.3
 
  phpmyadmin:
    image: phpmyadmin
    container_name: "vdi-panel-phpmyadmin"
    restart: always
    ports:
      - ${VDI_PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      newsvit-br:
        ipv4_address: 192.168.100.4