# Generated by Django 3.2.19 on 2023-08-30 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='نام تحویل گیرنده')),
                ('owner_user', models.CharField(max_length=100, unique=True, verbose_name='کاربری')),
                ('owner_password', models.CharField(max_length=100, verbose_name='پسورد')),
                ('owner_ip', models.CharField(default='1.1.1.1', max_length=100, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='آیپی کانتینر')),
                ('owner_browser_ip', models.CharField(default='1.1.1.1', max_length=100, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='آیپی فایل منیجر')),
                ('owner_vd_created_number', models.IntegerField(default=0, verbose_name='تعداد ساخته شده')),
                ('owner_description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('owner_create_by_ldap', models.BooleanField(blank=True, verbose_name='LDAP')),
                ('owner_is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('owner_created_at', models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='تاریخ ایجاد کاربر')),
                ('owner_updated_at', models.DateTimeField(auto_now=True, max_length=100, verbose_name='آخرین میزکار')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایلها',
            },
        ),
        migrations.CreateModel(
            name='VDIServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(blank=True, max_length=255, verbose_name='مسیر داده ها')),
                ('server_name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='اسم سرور')),
                ('server_ip', models.CharField(blank=True, max_length=25, verbose_name='آدرس سرور')),
                ('server_port', models.CharField(blank=True, max_length=25, verbose_name='پورت سرور')),
                ('server_scheme', models.CharField(blank=True, max_length=25, verbose_name='تنظیم ssl')),
                ('server_hostname', models.CharField(blank=True, max_length=25, verbose_name='دامنه سرور')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': ' سرور ',
                'verbose_name_plural': 'سرور ها',
            },
        ),
        migrations.CreateModel(
            name='VirtualDesktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vd_container_name', models.CharField(blank=True, max_length=100, verbose_name='نام میزکار')),
                ('vd_container_cpu', models.CharField(blank=True, max_length=25, verbose_name='مقدار پردازنده')),
                ('vd_container_mem', models.CharField(blank=True, max_length=25, verbose_name='مقدار حافظه')),
                ('vd_container_img', models.CharField(blank=True, max_length=255, verbose_name=' ایمیج')),
                ('vd_container_id', models.CharField(blank=True, max_length=255, verbose_name=' شناسه کانتینر')),
                ('vd_container_shortid', models.CharField(blank=True, max_length=255, verbose_name=' شناسه کوتاه کانتینر')),
                ('vd_container_user', models.CharField(blank=True, max_length=25, verbose_name=' کاربری میزکار')),
                ('vd_container_password', models.CharField(blank=True, max_length=25, verbose_name=' پسورد میزکار')),
                ('vd_container_vncpass', models.CharField(blank=True, max_length=25, verbose_name=' پسوردvnc')),
                ('vd_browser_id', models.CharField(blank=True, max_length=255, verbose_name=' شناسه فایل منیجر')),
                ('vd_browser_img', models.CharField(blank=True, max_length=255, verbose_name=' ایمیج فایل منیجر')),
                ('vd_browser_name', models.CharField(blank=True, max_length=255, verbose_name=' نام فایل منیجر')),
                ('vd_browser_pass', models.CharField(blank=True, max_length=255, verbose_name=' پسورد فایل منیجر')),
                ('vd_letter_number', models.IntegerField(blank=True, default=1111, verbose_name='شماره نامه')),
                ('vd_description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('vd_creator_ip', models.CharField(blank=True, max_length=255, verbose_name=' آیپی ایجاد کننده')),
                ('vd_is_activate', models.BooleanField(default=True, verbose_name='فعال')),
                ('vd_created_by', models.CharField(blank=True, max_length=255, verbose_name='ایجاد کننده')),
                ('vd_created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('vd_revoked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ابطال')),
                ('vd_expired_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('vd_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdiApp.userprofile', verbose_name='تحویل گیرنده')),
            ],
            options={
                'verbose_name': ' میزکار ',
                'verbose_name_plural': 'میزکار ها',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vdiApp.vdiserver', verbose_name='سرور'),
        ),
    ]
