# Generated by Django 3.2.19 on 2023-08-24 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_revoked_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 4, 56, 19, 973650), verbose_name='تاریخ ابطال'),
        ),
    ]
