# Generated by Django 3.2.19 on 2023-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_user', models.IntegerField()),
            ],
            options={
                'verbose_name': 'مشخصات سامانه',
            },
        ),
    ]
