# Generated by Django 3.2.19 on 2023-06-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualdesktop',
            name='vd_browser_id',
            field=models.CharField(blank=True, max_length=255, verbose_name=' شناسه فایل منیجر'),
        ),
        migrations.AddField(
            model_name='virtualdesktop',
            name='vd_browser_name',
            field=models.CharField(blank=True, max_length=255, verbose_name=' نام فایل منیجر'),
        ),
        migrations.AddField(
            model_name='virtualdesktop',
            name='vd_browser_port',
            field=models.CharField(blank=True, max_length=255, verbose_name=' پورت فایل منیجر'),
        ),
    ]
