# Generated by Django 3.2.19 on 2023-08-13 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='نام تحویل گیرنده')),
                ('owner_user', models.CharField(max_length=100, unique=True, verbose_name='کاربری')),
                ('owner_password', models.CharField(max_length=100, unique=True, verbose_name='پسورد')),
                ('owner_ip', models.CharField(default='1.1.1.1', max_length=100, validators=[django.core.validators.validate_ipv4_address], verbose_name='آیپی کانتینر')),
                ('owner_browser_ip', models.CharField(default='1.1.1.1', max_length=100, validators=[django.core.validators.validate_ipv4_address], verbose_name='آیپی کانتینر')),
                ('owner_vd_created_number', models.IntegerField(default=0, verbose_name='تعداد ساخته شده')),
                ('owner_description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('owner_is_active', models.BooleanField(default=True, verbose_name='فعال بودن کاربری')),
                ('owner_created_at', models.DateTimeField(auto_now=True, max_length=100, verbose_name='تاریخ ایجاد کاربر')),
                ('owner_updated_at', models.DateTimeField(auto_now=True, max_length=100, verbose_name='آخرین میزکار')),
            ],
            options={
                'verbose_name': 'دارنده میزکار',
                'verbose_name_plural': 'دارندگان میزکار',
            },
        ),
        migrations.RemoveField(
            model_name='virtualdesktop',
            name='vd_browser_port',
        ),
        migrations.RemoveField(
            model_name='virtualdesktop',
            name='vd_port',
        ),
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vdiApp.userprofile', verbose_name='تحویل گیرنده'),
        ),
    ]
