# Generated by Django 3.2 on 2023-06-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vdiserver',
            old_name='vd_server_ip',
            new_name='server_ip',
        ),
        migrations.RenameField(
            model_name='vdiserver',
            old_name='vd_server_name',
            new_name='server_name',
        ),
    ]
