# Generated by Django 3.2.19 on 2023-08-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0002_auto_20230813_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایلها'},
        ),
    ]
