# Generated by Django 3.2.19 on 2023-11-29 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0002_vdiinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vdiinfo',
            options={'verbose_name': 'مشخصات ', 'verbose_name_plural': 'مشخصات سامانه'},
        ),
        migrations.AddField(
            model_name='vdiinfo',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vdiinfo',
            name='limit_user',
            field=models.IntegerField(verbose_name='تعداد کاربر مجاز'),
        ),
    ]
