# Generated by Django 3.2.19 on 2023-06-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0002_auto_20230627_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualdesktop',
            name='vd_browser_img',
            field=models.CharField(blank=True, max_length=255, verbose_name=' ایمیج فایل منیجر'),
        ),
    ]
