# Generated by Django 3.2 on 2023-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0002_auto_20230625_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_creator_ip',
            field=models.CharField(blank=True, max_length=255, verbose_name=' آیپی کاربر'),
        ),
    ]
