# Generated by Django 3.2.19 on 2023-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0003_auto_20231129_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdiinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام سازمان'),
        ),
    ]
