# Generated by Django 3.2.19 on 2023-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner_create_by_ldap',
            field=models.TextField(blank=True, verbose_name='is LDAP'),
        ),
    ]
