# Generated by Django 3.2.19 on 2023-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0004_userprofile_owner_create_by_ldap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='owner_create_by_ldap',
            field=models.BooleanField(blank=True, verbose_name='is LDAP'),
        ),
    ]
