# Generated by Django 3.2.19 on 2023-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0005_vdiinfo_company_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdiinfo',
            name='api_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
