# Generated by Django 3.2.19 on 2023-08-17 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0005_alter_userprofile_owner_create_by_ldap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='owner_browser_ip',
            field=models.CharField(default='1.1.1.1', max_length=100, validators=[django.core.validators.validate_ipv4_address], verbose_name='آیپی فایل منیجر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner_created_at',
            field=models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='تاریخ ایجاد کاربر'),
        ),
    ]
