# Generated by Django 3.2.19 on 2023-08-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0007_vdiserver_server_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_revoked_at',
            field=models.DateTimeField(blank=True, verbose_name='تاریخ ابطال'),
        ),
    ]
