# Generated by Django 3.2.19 on 2023-08-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0008_auto_20230817_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdiApp.userprofile', verbose_name='تحویل گیرنده'),
        ),
    ]
