# Generated by Django 3.2.19 on 2023-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0009_alter_virtualdesktop_vd_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='owner_create_by_ldap',
            field=models.BooleanField(blank=True, verbose_name='LDAP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner_is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_revoked_at',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='تاریخ ابطال'),
        ),
    ]
