# Generated by Django 3.2.19 on 2023-08-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0010_auto_20230819_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_revoked_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ابطال'),
        ),
    ]
