# Generated by Django 3.2.19 on 2023-08-19 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0011_alter_virtualdesktop_vd_revoked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 7, 58, 51, 958283), verbose_name='تاریخ ایجاد'),
        ),
    ]
