# Generated by Django 3.2.19 on 2023-08-19 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0012_alter_virtualdesktop_vd_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='virtualdesktop',
            name='vd_revoked_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 20, 8, 1, 57, 734323), verbose_name='تاریخ ابطال'),
        ),
    ]
